CXX=g++
CXXFLAGS=-std=c++17 -Wall -Werror -O2 -I.

# autogenerated-lists-begin
BINARIES= \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver \
	orlodrimbot/live_replication/live_replication \
	orlodrimbot/monthly_categories_init/monthly_categories_init \
	orlodrimbot/sandbox/sandbox
TESTS= \
	cbl/path_test \
	mwclient/tests/parser_misc_test \
	mwclient/tests/parser_nodes_test \
	mwclient/tests/parser_test \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib_test \
	orlodrimbot/live_replication/recent_changes_reader_test \
	orlodrimbot/live_replication/recent_changes_sync_test \
	orlodrimbot/wikiutil/date_parser_test
# autogenerated-lists-end

.PHONY: all check clean

all: $(BINARIES)
check: $(TESTS)
	for bin in $^; do $${bin}; done; echo SUCCESS
clean:
	rm -f */*.[ao] */*/*.[ao] $(BINARIES) $(TESTS)

# autogenerated-rules-begin
cbl/args_parser.o: cbl/args_parser.cpp cbl/args_parser.h cbl/error.h cbl/generated_range.h cbl/string.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/date.o: cbl/date.cpp cbl/date.h cbl/error.h cbl/log.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/error.o: cbl/error.cpp cbl/error.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/file.o: cbl/file.cpp cbl/error.h cbl/file.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/html_entities.o: cbl/html_entities.cpp cbl/html_entities.h cbl/utf8.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/http_client.o: cbl/http_client.cpp cbl/error.h cbl/generated_range.h cbl/http_client.h cbl/string.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/json.o: cbl/json.cpp cbl/error.h cbl/json.h cbl/utf8.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/log.o: cbl/log.cpp cbl/log.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/path.o: cbl/path.cpp cbl/path.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/path_test.o: cbl/path_test.cpp cbl/log.h cbl/path.h cbl/unittest.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/path_test: cbl/path_test.o cbl/unittest.o mwclient/libmwclient.a
	$(CXX) -o $@ $^
cbl/sqlite.o: cbl/sqlite.cpp cbl/error.h cbl/file.h cbl/log.h cbl/sqlite.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/string.o: cbl/string.cpp cbl/error.h cbl/generated_range.h cbl/string.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/tempfile.o: cbl/tempfile.cpp cbl/error.h cbl/tempfile.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/unicode_fr.o: cbl/unicode_fr.cpp cbl/unicode_fr.h cbl/utf8.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/unittest.o: cbl/unittest.cpp cbl/log.h cbl/unittest.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
cbl/utf8.o: cbl/utf8.cpp cbl/utf8.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/bot_exclusion.o: mwclient/bot_exclusion.cpp cbl/generated_range.h cbl/string.h mwclient/bot_exclusion.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/mock_wiki.o: mwclient/mock_wiki.cpp cbl/date.h cbl/error.h cbl/generated_range.h cbl/json.h \
	cbl/log.h cbl/string.h mwclient/mock_wiki.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/parser.o: mwclient/parser.cpp cbl/error.h cbl/generated_range.h cbl/log.h mwclient/parser.h \
	mwclient/parser_misc.h mwclient/parser_nodes.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/parser_misc.o: mwclient/parser_misc.cpp cbl/generated_range.h cbl/string.h mwclient/parser_misc.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/parser_nodes.o: mwclient/parser_nodes.cpp cbl/generated_range.h cbl/json.h cbl/log.h cbl/string.h \
	mwclient/parser_misc.h mwclient/parser_nodes.h mwclient/site_info.h mwclient/titles_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/request.o: mwclient/request.cpp cbl/date.h cbl/error.h cbl/generated_range.h cbl/json.h cbl/log.h \
	cbl/string.h mwclient/request.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/site_info.o: mwclient/site_info.cpp cbl/error.h cbl/json.h cbl/unicode_fr.h cbl/utf8.h \
	mwclient/site_info.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/tests/parser_misc_test.o: mwclient/tests/parser_misc_test.cpp cbl/log.h cbl/unittest.h \
	mwclient/parser_misc.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/tests/parser_misc_test: mwclient/tests/parser_misc_test.o cbl/unittest.o mwclient/libmwclient.a
	$(CXX) -o $@ $^
mwclient/tests/parser_nodes_test.o: mwclient/tests/parser_nodes_test.cpp cbl/error.h cbl/generated_range.h \
	cbl/log.h cbl/unittest.h mwclient/parser.h mwclient/parser_misc.h mwclient/parser_nodes.h \
	mwclient/tests/parser_test_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/tests/parser_nodes_test: mwclient/tests/parser_nodes_test.o cbl/unittest.o \
	mwclient/tests/parser_test_util.o mwclient/libmwclient.a
	$(CXX) -o $@ $^
mwclient/tests/parser_test.o: mwclient/tests/parser_test.cpp cbl/error.h cbl/generated_range.h cbl/log.h \
	cbl/unittest.h mwclient/parser.h mwclient/parser_misc.h mwclient/parser_nodes.h \
	mwclient/tests/parser_test_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/tests/parser_test: mwclient/tests/parser_test.o cbl/unittest.o mwclient/tests/parser_test_util.o \
	mwclient/libmwclient.a
	$(CXX) -o $@ $^
mwclient/tests/parser_test_util.o: mwclient/tests/parser_test_util.cpp cbl/error.h cbl/generated_range.h \
	mwclient/parser.h mwclient/parser_misc.h mwclient/parser_nodes.h mwclient/tests/parser_test_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/titles_util.o: mwclient/titles_util.cpp cbl/generated_range.h cbl/html_entities.h cbl/json.h \
	cbl/string.h cbl/unicode_fr.h cbl/utf8.h mwclient/site_info.h mwclient/titles_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/util/init_wiki.o: mwclient/util/init_wiki.cpp cbl/args_parser.h cbl/date.h cbl/error.h cbl/file.h \
	cbl/generated_range.h cbl/json.h cbl/log.h cbl/path.h cbl/string.h mwclient/site_info.h \
	mwclient/titles_util.h mwclient/util/init_wiki.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki.o: mwclient/wiki.cpp cbl/date.h cbl/error.h cbl/http_client.h cbl/json.h cbl/unicode_fr.h \
	cbl/utf8.h mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_base.o: mwclient/wiki_base.cpp cbl/date.h cbl/error.h cbl/http_client.h cbl/json.h cbl/log.h \
	mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_defs.o: mwclient/wiki_defs.cpp cbl/date.h cbl/error.h cbl/generated_range.h cbl/log.h \
	cbl/string.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_read_api.o: mwclient/wiki_read_api.cpp cbl/date.h cbl/error.h cbl/http_client.h cbl/json.h \
	mwclient/request.h mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_read_api_query_list.o: mwclient/wiki_read_api_query_list.cpp cbl/date.h cbl/error.h \
	cbl/generated_range.h cbl/json.h cbl/log.h cbl/string.h mwclient/request.h mwclient/site_info.h \
	mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_read_api_query_prop.o: mwclient/wiki_read_api_query_prop.cpp cbl/date.h cbl/error.h \
	cbl/generated_range.h cbl/json.h cbl/log.h cbl/string.h mwclient/bot_exclusion.h mwclient/request.h \
	mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_session.o: mwclient/wiki_session.cpp cbl/date.h cbl/error.h cbl/file.h cbl/generated_range.h \
	cbl/http_client.h cbl/json.h cbl/log.h cbl/string.h mwclient/request.h mwclient/site_info.h \
	mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
mwclient/wiki_write_api.o: mwclient/wiki_write_api.cpp cbl/date.h cbl/error.h cbl/json.h mwclient/request.h \
	mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/bot_requests_archiver/bot_requests_archiver.o: orlodrimbot/bot_requests_archiver/bot_requests_archiver.cpp \
	cbl/args_parser.h cbl/date.h cbl/error.h cbl/json.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/util/init_wiki.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/bot_requests_archiver/bot_requests_archiver: orlodrimbot/bot_requests_archiver/bot_requests_archiver.o \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.o orlodrimbot/wikiutil/libwikiutil.a \
	mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl -lre2
orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.o: \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.cpp cbl/date.h cbl/error.h \
	cbl/generated_range.h cbl/json.h cbl/log.h cbl/string.h mwclient/parser.h mwclient/parser_misc.h \
	mwclient/parser_nodes.h mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.h \
	orlodrimbot/wikiutil/date_parser.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib_test.o: \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib_test.cpp cbl/date.h cbl/error.h cbl/json.h \
	cbl/log.h cbl/unittest.h mwclient/mock_wiki.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib_test: \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib_test.o cbl/unittest.o \
	orlodrimbot/bot_requests_archiver/bot_requests_archiver_lib.o orlodrimbot/wikiutil/libwikiutil.a \
	mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl -lre2
orlodrimbot/live_replication/continue_token.o: orlodrimbot/live_replication/continue_token.cpp cbl/error.h \
	cbl/generated_range.h cbl/string.h orlodrimbot/live_replication/continue_token.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/live_replication/live_replication.o: orlodrimbot/live_replication/live_replication.cpp cbl/args_parser.h \
	cbl/date.h cbl/error.h cbl/json.h cbl/path.h cbl/sqlite.h mwclient/site_info.h \
	mwclient/titles_util.h mwclient/util/init_wiki.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h orlodrimbot/live_replication/recent_changes_reader.h \
	orlodrimbot/live_replication/recent_changes_sync.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/live_replication/live_replication: orlodrimbot/live_replication/live_replication.o cbl/sqlite.o \
	orlodrimbot/live_replication/continue_token.o orlodrimbot/live_replication/recent_changes_reader.o \
	orlodrimbot/live_replication/recent_changes_sync.o mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl -lsqlite3
orlodrimbot/live_replication/recent_changes_reader.o: orlodrimbot/live_replication/recent_changes_reader.cpp \
	cbl/date.h cbl/error.h cbl/json.h cbl/log.h cbl/sqlite.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h orlodrimbot/live_replication/continue_token.h \
	orlodrimbot/live_replication/recent_changes_reader.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/live_replication/recent_changes_reader_test.o: orlodrimbot/live_replication/recent_changes_reader_test.cpp \
	cbl/date.h cbl/error.h cbl/generated_range.h cbl/json.h cbl/log.h cbl/sqlite.h cbl/string.h \
	cbl/tempfile.h cbl/unittest.h mwclient/mock_wiki.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h \
	orlodrimbot/live_replication/recent_changes_reader.h orlodrimbot/live_replication/recent_changes_sync.h \
	orlodrimbot/live_replication/recent_changes_test_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/live_replication/recent_changes_reader_test: orlodrimbot/live_replication/recent_changes_reader_test.o \
	cbl/sqlite.o cbl/tempfile.o cbl/unittest.o orlodrimbot/live_replication/continue_token.o \
	orlodrimbot/live_replication/recent_changes_reader.o orlodrimbot/live_replication/recent_changes_sync.o \
	orlodrimbot/live_replication/recent_changes_test_util.o mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl -lsqlite3
orlodrimbot/live_replication/recent_changes_sync.o: orlodrimbot/live_replication/recent_changes_sync.cpp cbl/date.h \
	cbl/error.h cbl/json.h cbl/log.h cbl/sqlite.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h \
	orlodrimbot/live_replication/recent_changes_sync.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/live_replication/recent_changes_sync_test.o: orlodrimbot/live_replication/recent_changes_sync_test.cpp \
	cbl/date.h cbl/error.h cbl/json.h cbl/log.h cbl/sqlite.h cbl/tempfile.h cbl/unittest.h \
	mwclient/mock_wiki.h mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h orlodrimbot/live_replication/recent_changes_sync.h \
	orlodrimbot/live_replication/recent_changes_test_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/live_replication/recent_changes_sync_test: orlodrimbot/live_replication/recent_changes_sync_test.o \
	cbl/sqlite.o cbl/tempfile.o cbl/unittest.o orlodrimbot/live_replication/recent_changes_sync.o \
	orlodrimbot/live_replication/recent_changes_test_util.o mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl -lsqlite3
orlodrimbot/live_replication/recent_changes_test_util.o: orlodrimbot/live_replication/recent_changes_test_util.cpp \
	cbl/date.h cbl/error.h cbl/json.h cbl/log.h mwclient/mock_wiki.h mwclient/site_info.h \
	mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h \
	orlodrimbot/live_replication/recent_changes_test_util.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/monthly_categories_init/monthly_categories_init.o: \
	orlodrimbot/monthly_categories_init/monthly_categories_init.cpp cbl/args_parser.h cbl/date.h cbl/error.h \
	cbl/generated_range.h cbl/json.h cbl/log.h cbl/string.h mwclient/site_info.h mwclient/titles_util.h \
	mwclient/util/init_wiki.h mwclient/wiki.h mwclient/wiki_base.h mwclient/wiki_defs.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/monthly_categories_init/monthly_categories_init: \
	orlodrimbot/monthly_categories_init/monthly_categories_init.o mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl
orlodrimbot/sandbox/sandbox.o: orlodrimbot/sandbox/sandbox.cpp cbl/args_parser.h cbl/date.h cbl/error.h \
	cbl/json.h mwclient/site_info.h mwclient/titles_util.h mwclient/util/init_wiki.h mwclient/wiki.h \
	mwclient/wiki_base.h mwclient/wiki_defs.h orlodrimbot/sandbox/sandbox_lib.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/sandbox/sandbox: orlodrimbot/sandbox/sandbox.o orlodrimbot/sandbox/sandbox_lib.o \
	mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lcurl
orlodrimbot/sandbox/sandbox_lib.o: orlodrimbot/sandbox/sandbox_lib.cpp cbl/date.h cbl/error.h cbl/json.h \
	cbl/log.h mwclient/site_info.h mwclient/titles_util.h mwclient/wiki.h mwclient/wiki_base.h \
	mwclient/wiki_defs.h orlodrimbot/sandbox/sandbox_lib.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/wikiutil/date_parser.o: orlodrimbot/wikiutil/date_parser.cpp cbl/date.h cbl/unicode_fr.h cbl/utf8.h \
	orlodrimbot/wikiutil/date_parser.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/wikiutil/date_parser_test.o: orlodrimbot/wikiutil/date_parser_test.cpp cbl/date.h cbl/log.h \
	cbl/unittest.h orlodrimbot/wikiutil/date_parser.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<
orlodrimbot/wikiutil/date_parser_test: orlodrimbot/wikiutil/date_parser_test.o cbl/unittest.o \
	orlodrimbot/wikiutil/libwikiutil.a mwclient/libmwclient.a
	$(CXX) -o $@ $^ -lre2
mwclient/libmwclient.a: cbl/args_parser.o cbl/date.o cbl/error.o cbl/file.o cbl/html_entities.o \
	cbl/http_client.o cbl/json.o cbl/log.o cbl/path.o cbl/string.o cbl/unicode_fr.o cbl/utf8.o \
	mwclient/bot_exclusion.o mwclient/mock_wiki.o mwclient/parser.o mwclient/parser_misc.o \
	mwclient/parser_nodes.o mwclient/request.o mwclient/site_info.o mwclient/titles_util.o \
	mwclient/util/init_wiki.o mwclient/wiki.o mwclient/wiki_base.o mwclient/wiki_defs.o \
	mwclient/wiki_read_api.o mwclient/wiki_read_api_query_list.o mwclient/wiki_read_api_query_prop.o \
	mwclient/wiki_session.o mwclient/wiki_write_api.o
	ar rcs $@ $^
orlodrimbot/wikiutil/libwikiutil.a: orlodrimbot/wikiutil/date_parser.o
	ar rcs $@ $^
# autogenerated-rules-end
